I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 28, in script
    e "You've created a new Ren'Py game."
IOError: Couldn't find file '01 Doki Doki Literature Club!.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 28, in script
    e "You've created a new Ren'Py game."
  File "renpy/ast.py", line 706, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1384, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1179, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "renpy/character.py", line 851, in do_display
    **display_args)
  File "renpy/character.py", line 601, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 2978, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "renpy/display/core.py", line 3660, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1106, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1084, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1026, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 492, in periodic
    topf = load(self.file_prefix + filename + self.file_suffix)
  File "renpy/audio/audio.py", line 74, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 766, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file '01 Doki Doki Literature Club!.mp3'.

